### ISSUE TITLE
Add setup instructions

### ISSUE THREAD

**Issue by robinske** [scalabridge/curriculum#7]
Terminal (how to access)
Java
Scala 
Brew (or other package management)
IntelliJ?

Have guide per Operating System

**Comment by robinske** [comment]
The setup chapters here are super useful: http://www.atomicscala.com/free-sample/#.V5zujZMrJE4

**Comment by sdkarlson** [comment]
Yoink

**Comment by k4y3ff** [comment]
> IntelliJ?

Not sure what route y'all are going on this, but I'd really avoid using IntelliJ for workshops! It's not unreasonable to learn IntelliJ alongside a language in a months-long course, but for a two-day workshop, it turns out to be too much to hold in your head at once.

Atomic Scala recommends Sublime, which is indeed cool! It's what I used to learn Scala, so I'm of course biased towards it.

That being said: I would strongly encourage Atom over Sublime, mostly because of the pop-ups. It's true that you can just close them, but a lot of folks who come to RailsBridge and ClojureBridge workshops can't afford to spend a lot of money on learning resources, so having a pop-up constantly asking them for money would be pretty problematic. I envision this being the case for some folks learning Scala, as well.

I now use Atom day-to-day, and there's nothing from Sublime that I miss.

**Comment by k4y3ff** [comment]
Also! Atom bonus: installing packages is way more beginner-friendly with Atom than with Sublime.

**Comment by robinske** [comment]
Excellent feedback! This is all stuff we need to hear!

**Comment by k4y3ff** [comment]
NP! Also: make sure to have folks install a package for rainbow brackets! They come in handy.

There are lots of packages for this, but I use [swackets](https://atom.io/packages/swackets) for Atom, and it's 👌

**Comment by tim-ruhland** [comment]
@kpfell recommending atom for editing for those that need it at the workshop is a good idea. I can work on a setup page for the editor. I am not an atom user (or wasn't until today), can you recommend which packages are the "essentials" for Scala developer?

**Comment by MarceStarlet** [comment]
Hi all o/

I agree with the idea of use atom. If someone is working on this please let me know so I can help with the redaction of the instructions in a specific Operative System. I use mac by default but I can contribute with other OS if needed.

**Comment by robinske** [comment]
Done! https://github.com/scalabridge/curriculum/tree/master/setup
